### PR TITLE
Remove CircleCI

### PR DESCRIPTION
**Pull request by davydog187**
Github actions appears to be the CI system now

### CODE REVIEW

**Comment by davydog187** [comment]
CircleCI and github actions don't have 100% parity. Its unclear to me what needs to be moved over, if anything

**Comment by tsloughter** [comment]
Thanks! This is all that is needed except it is blocked because it, of course, breaks the circleci build and I need to figure out how to tell github to not care about it anymore...

**Comment by SergeyKanzhelev** [comment]
> Thanks! This is all that is needed except it is blocked because it, of course, breaks the circleci build and I need to figure out how to tell github to not care about it anymore...

It looks like it was already done. It is not a required check on this branch in settings. Let me know if some help is needed here

**Comment by davydog187** [comment]
@tsloughter you can do that via Settings -> Branches -> (Edit) Master -> Uncheck circle ci under `Require status checks to pass before merging`

**Comment by SergeyKanzhelev** [comment]
> @tsloughter you can do that via Settings -> Branches -> (Edit) Master -> Uncheck circle ci under `Require status checks to pass before merging`

it is already unchecked. You can see it in this PR essage - there is no "Required" label:

image

**Review by tsloughter — APPROVED** [review]

**Comment by tsloughter** [comment]
Yup, my bad it was only blocked since I hadn't approved it yet :), thanks @SergeyKanzhelev

**Pull request merged**
