### PR TITLE
Clean repo and write redirect README

### PR DESCRIPTION
**Pull request by hauleth**
After merging this the repo should be marked as archived.

### CODE REVIEW

**Comment by ferd** [comment]
Would it make more sense to just rewrite the README and then archive this repo rather than just get rid of all its content?

**Comment by tsloughter** [comment]
Yea, I thought what Fred said was the plan, @hauleth ?

**Comment by hauleth** [comment]
@tsloughter @ferd my point in ditching it all is just in case someone used Git dependency with master and missed the merging, so they will not end with outdated code (as it will painfully break for them).

**Comment by ferd** [comment]
It will sooner or later break when they rely on the other repo for something else, though I'd not consider "forcing a hard break" to be a good feature on that stuff.

**Comment by hauleth** [comment]
@ferd I would say that sooner is better in this case. It will make the errors clearer and will not confuse reporters and maintainers with strange reports.

**Comment by bryannaegele** [comment]
There's only 12 forks and half of them are us. 🤷🏻

**Comment by bryannaegele** [comment]
We don't need to delete everything. They can archive the repo which just puts it in a read-only state.

I'd say just update the readme, close out the issues, and ask for it to be archived.

**Comment by tsloughter** [comment]
@hauleth are you ok changing this to just the readme update?

**Pull request closed without merging**
